name: C/C++ CI

on: [push, pull]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: tests
      run: |
        cd tests
        make
        ./test
